services:
  postgres:
    image: postgres:15-alpine
    container_name: gestao_alunos_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Escola@2024
      POSTGRES_DB: gestao_alunos
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: gestao_alunos_backend
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: Escola@2024
      DB_NAME: gestao_alunos
      JWT_SECRET: minha_chave_secreta_123
      JWT_EXPIRES_IN: 7d
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules

volumes:
  postgres_data: